# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

stages:
- stage: 'Ressources Azure'
  pool:
    vmImage: ubuntu-latest
  displayName: 'Approvisionnement des ressources Azure'
  variables:
    serviceConnection : 'InfonuagiqueAzure'
    resourceGroupName: 'rg-tp2-autorapide-postch'
    location: 'canadacentral'
    templateFile: '**/bicep/main.bicep'
    webAppName: 'AutoRapide'
  jobs:
    - job: 'AzureCLI'
      displayName: 'Exécution du script bicep'
      steps:
        - task: AzureCLI@2
          env:
            DBADMINLOGIN: $(dbAdminLogin)
            DBADMINPASSWORD: $(dbAdminPassword)
          inputs:
            azureSubscription: $(serviceConnection)
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az --version
              az group create --name $(resourceGroupName) --location $(location)
              az deployment group create --resource-group $(resourceGroupName) --template-file $(templateFile) --parameters appName=$(webAppName) dbAdminLogin=$DBADMINLOGIN dbAdminPassword=$DBADMINPASSWORD
          displayName: 'Environnement de Développement'