// <auto-generated />
using AutoRapide.Vehicules.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutoRapide.Vehicules.API.Migrations
{
    [DbContext(typeof(VehiculeContext))]
    [Migration("20220105194709_MigrationInitiale")]
    partial class MigrationInitiale
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("AutoRapide.Vehicules.API.Entities.Vehicule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnneeFabrication")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Constructeur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Couleur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("EstDisponible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image1Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image2Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modele")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NIV")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NombreSiege")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Prix")
                        .HasColumnType("REAL");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Vehicule", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
