# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
  buildConfiguration: 'Release'
  serviceConnection : 'InfonuagiqueAzure'

stages:
- stage : 'Build' 
  displayName:  'Build, execution des tests et publication'
  pool:
    vmImage: 'ubuntu-latest'
  jobs:
    - job : 'Build'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
         command: 'restore'
         projects: '**/*.csproj'
         feedsToUse: 'select'
        displayName: 'Restaurer les packages'
      - task: DotNetCoreCLI@2
        inputs:
         command: 'build'
         projects: '**/*.csproj'
         arguments: '--configuration $(buildConfiguration)'
        displayName: 'Génération de la solution'
      - task: DotNetCoreCLI@2
        inputs:
         command: 'test'
         projects: '**/*Tests.csproj'
         arguments: '--configuration $(buildConfiguration)'
        displayName: 'Exécution des tests unitaires'
      - task: DotNetCoreCLI@2
        inputs:
         command: 'publish'
         publishWebProjects: true
         arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        displayName: 'Génération du package de publication'
      - task: DotNetCoreCLI@2
        inputs:
         command: 'publish'
         publishWebProjects: false
         projects: 'src/**/*API.csproj'
         arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        displayName: 'Génération du package de publication'
      - task: PublishBuildArtifacts@1
        inputs:
         PathtoPublish: '$(Build.ArtifactStagingDirectory)'
         ArtifactName: 'drop'
         publishLocation: 'Container'
        displayName: 'Publication du package dans Azure DevOps'
        
- stage : 'DeployToDev' 
  displayName:  'Déploiment en Dev'
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: 'Build'
  jobs:
    - deployment : 'DeployAPIs'
      environment: 'h22-developpement'
      strategy:
        runOnce:
         deploy:
           steps:
           - task: DownloadBuildArtifacts@0
             inputs:
               buildType: 'current'
               downloadType:  'single'
               artifactName: 'drop'
               downloadPath: '$(System.ArtifactsDirectory)'
             displayName: 'Téléchargement du package'
           - task: AzureRmWebAppDeployment@4
             inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: 'UsagerAPI-ov7wal3dh27xs'
              package: '$(Build.ArtifactStagingDirectory)/**/*AutoRapide.Utilisateurs.API.zip'
             displayName: 'Déploiement d''UsagerAPI'
           - task: AzureRmWebAppDeployment@4
             inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: 'VehiculesAPI-ov7wal3dh27xs'
              package: '$(Build.ArtifactStagingDirectory)/AutoRapide.Vehicules.API.zip'
             displayName: 'Déploiement de VehiculesAPI'
           - task: AzureRmWebAppDeployment@4
             inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: 'CommandesAPI-ov7wal3dh27xs'
              package: '$(Build.ArtifactStagingDirectory)/**/*AutoRapide.Commandes.API.zip'
             displayName: 'Déploiement de CommandesAPI'
           - task: AzureRmWebAppDeployment@4
             inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: 'FichiersAPI-ov7wal3dh27xs'
              package: '$(Build.ArtifactStagingDirectory)/**/*AutoRapide.Fichiers.API.zip'
             displayName: 'Déploiement de FichiersAPI'
           - task: AzureRmWebAppDeployment@4
             inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: '$(serviceConnection)'
              appType: 'webApp'
              WebAppName: 'FavorisAPI-ov7wal3dh27xs'
              package: '$(Build.ArtifactStagingDirectory)/**/*AutoRapide.Favoris.API.zip'
             displayName: 'Déploiement de FavorisAPI'
    - deployment : 'DeployClient'
      dependsOn: 'DeployAPIs'
      environment: 'h22-developpement'
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadBuildArtifacts@0
              inputs:
               buildType: 'current'
               downloadType:  'single'
               artifactName: 'drop'
               downloadPath: '$(System.ArtifactsDirectory)'
              displayName: 'Téléchargement du package'
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: '$(serviceConnection)'
                appType: 'webApp'
                WebAppName: 'AutoRapideMVC-ov7wal3dh27xs'
                package: '$(Build.ArtifactStagingDirectory)/**/*AutoRapide.MVC.zip'
              displayName: 'Déploiement de AutoRapideMVC'

